name: Build and Publish to PyPI

on:
  release:
    types:
      - published

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.5.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Install the package
        run: poetry install --no-dev
      - name: Check the version
        run: test $(poetry version --short) = ${{ github.ref_name }}
      - name: Build and publish to pypi
        run: |
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
