name: Build and Publish to PyPI

on:
  push:
    tags:
      - "*.*.*"

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: 1.1.15

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Check the version
        run: test $(poetry version --short) = ${{ github.ref_name }}
      - name: Build and publish to pypi
        run: |
          poetry install --no-dev
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
